name:                connect4points
version:             0.1.0.0
github:              "githubuser/connect4points"
license:             BSD3
author:              Mateus Augusto, GUilherme e GUilherme
maintainer:          "example@example.com"
copyright:           "2019 Yash Srivastav <https://github.com/yashsriv/haskell-connect-4>"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/breaking-stopdigmas/connect4points/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- containers
- random
- gloss

library:
  source-dirs: src

executables:
  connect4points-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect4points

tests:
  connect4points-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect4points
